management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: pulseflow
    url: jdbc:postgresql://localhost:5432/pulseflow
    password: pulseflow
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
  application:
    name: rule-service
logging:
  level:
    org:
      springframework: INFO
    com:
      pulseflow: DEBUG
server:
  port: '8080'
springdoc:
  swagger-ui:
    path: /swagger-ui.html